language: objective-c
osx_image: xcode10.2

git:
    depth: 1

cache:
    directories:
        - Carthage

before_install: brew update && brew bundle

script:
    - ./bin/build_travis.sh

deploy:
  provider: releases
  api_key:
    secure:  ${GH_TOKEN}
  file: "build/Build/Products/Release/**"
  skip_cleanup: true
  on:
    tags: true
